config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'user/temples#index'

   namespace :admin do
     resources :temples, only: [:index, :show, :new, :edit, :update, :destroy, :create]
     get 'search', to: 'temples#search'
     get 'searchform', to: 'temples#searchform'
     resources :users, only: [:index, :show, :edit, :update, :destroy]
     resources :memorys, only: [:index, :show, :destroy]
     resources :contacts, only: [:index, :show, :update]
     resources :questions, only: [ :index,:show, :destroy] do
       resource :answers, only: [:destroy]
     end
   end
  namespace :user do
    get 'search', to: 'temples#search'
    get 'searchform', to: 'temples#searchform'
    resources :temples, only: [:index, :show, :edit, :update, :destroy] do
      resource :clips, only: [:create, :destroy]
    end
    resources :users, only: [:show, :new, :edit, :update, :destroy, :create]
    get 'top', to: 'users#top'
    resources :contacts, only: [ :new, :create]
    get 'top', to: 'users#top'
      get 'memorys/:id/new' => 'memorys#new', as: 'new_memory'
    post 'memorys/:id/create' => 'memorys#create', as: 'create_memory'
    resources :memorys, only: [:index, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :questions, only: [ :index,:show, :destroy, :create] do
      resource :answers, only: [ :new, :create,:destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
belongs_to :user
belongs_to :question

default_scope -> { order(created_at: :desc) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clip.rb
class Clip < ApplicationRecord

belongs_to :user
belongs_to :temple

from  = Time.now.at_beginning_of_day
to    = (from + 6.day).at_end_of_day

default_scope -> { order(created_at: :desc) }
end

app/models/contact.rb
class Contact < ApplicationRecord

belongs_to :user
# replyが空かどうかでバリデーションをかける、空ならユーザー、違えば管理者。
validates :contact, presence: true, if: :is_user?
validates :reply, presence: true, unless: :is_user?

private
# ユーザーか否かを判断するメソッド。replyが空の場合はユーザーと判断し、contactにのみバリデーションが働く。
def is_user?
	self.reply.nil?
end

default_scope -> { order(created_at: :desc) }
end

app/models/favorite.rb
class Favorite < ApplicationRecord

belongs_to :user
belongs_to :memory

end

app/models/goriyaku.rb
class Goriyaku < ApplicationRecord

has_many :temples, dependent: :destroy


end

app/models/memory.rb
class Memory < ApplicationRecord

	belongs_to :user
	belongs_to :temple
	has_many :favorites, dependent: :destroy
	has_many :memory_images, dependent: :destroy
  	accepts_attachments_for :memory_images, attachment: :image
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end
end

app/models/memory_image.rb
class MemoryImage < ApplicationRecord

	belongs_to :memory
  	attachment :image

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
	has_many :temples, dependent: :destroy
	has_many :users, dependent: :destroy

end

app/models/question.rb
class Question < ApplicationRecord
has_many :answers, dependent: :destroy
belongs_to :user
is_impressionable counter_cache: true

def self.search(search)
		if search
			where(['body LIKE ?', "%#{search}%"])
		else
			all
		end
	end


end

app/models/temple.rb
class Temple < ApplicationRecord

	has_many :memorys, dependent: :destroy
	belongs_to :prefecture
	belongs_to :goriyaku
	attachment :mainimage
	has_many :clips, dependent: :destroy
        def cliped_by?(user)
          clips.where(user_id: user.id).exists?
        end
    has_many :temple_images, dependent: :destroy
 	 accepts_attachments_for :temple_images, attachment: :image

	validates :prefecture_id, presence: true
	validates :goriyaku_id, presence: true

	after_validation :geocode

	  private
	  def geocode
	    uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=AIzaSyDV7aHnCQ6Lbws5KlkFCA7XzgB4So2mREE")
	    res = HTTP.get(uri).to_s
	    response = JSON.parse(res)
	    self.latitude = response["results"][0]["geometry"]["location"]["lat"]
	    self.longitude = response["results"][0]["geometry"]["location"]["lng"]
	  end


  	enum area: { 北海道: 1, 東北: 2, 関東: 3, 中部: 4, 近畿: 5,中国: 6, 四国: 7, 九州沖縄:8 }
end

app/models/temple_image.rb
class TempleImage < ApplicationRecord

	belongs_to :temple
  	attachment :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum gender: [ :'男性', :'女性' ]
  enum age: [ :'10代', :'20代', :'30代', :'40代', :'50代', :'60代以上' ]

  has_many :memorys, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :clips, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  attachment :profile_image
end

app/controllers/admin/memorys_controller.rb
class Admin::MemorysController < ApplicationController
  PER = 10
  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Memory.find(Favorite.where(created_at: from...to).group(:memory_id).order('count(memory_id) desc').limit(10).pluck(:memory_id))
    @memorys = Memory.page(params[:page]).per(PER).order(created_at: "DESC")
  end

  def destroy
      @memory = Memory.find(params[:id])
      @memory.destroy
      redirect_to user_user_path(current_user.id)
  end

  def edit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_sign_up_params,if: :devise_controller?


	protected
	def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :gender])
   end

   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :age, :gender])
   end

   private

  # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_temples_path
    else
      user_temples_path
    end
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_user_session_path
    end
  end


end

app/controllers/user/memorys_controller.rb
class User::MemorysController < ApplicationController
  PER = 10
  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Memory.find(Favorite.where(created_at: from...to).group(:memory_id).order('count(memory_id) desc').limit(10).pluck(:memory_id))
    @memorys = Memory.page(params[:page]).per(PER).order(created_at: "DESC")
  end

  def new
    @temple = Temple.find(params[:id])
  	@memory = Memory.new
    @memory.memory_images.build
  end

  def create
  	@temple = Temple.find(params[:id])
  	@memory = @temple.memorys.build(memory_params)
  	@memory.user_id = current_user.id
  	if
      @memory.save!
      redirect_to user_temple_path(@temple)
    else
      render :new
    end
  end

  def edit
    @memory = Memory.find(params[:id])
  end

  def update
    @memory = Memory.find(params[:id])
    if @memory.update(memory_params)
       flash[:notice] = "memoryを更新しました"
       redirect_to user_user_path(current_user.id)
    else
       render :edit
    end
  end

  def destroy
      @memory = Memory.find(params[:id])
      @memory.destroy
      redirect_to user_user_path(current_user.id)
  end

   private

  def memory_params
    params.require(:memory).permit(:user_id, :temple_id, :title, :body, :visit_date, memory_images_images: [])
  end
end

app/helpers/admin/memorys_helper.rb
module Admin::MemorysHelper
end

app/helpers/admin/ur_helper.rb
module Admin::UrHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/answers_helper.rb
module User::AnswersHelper
end

app/helpers/user/clips_helper.rb
module User::ClipsHelper
end

app/helpers/user/memorys_helper.rb
module User::MemorysHelper
end

app/helpers/user/user_helper.rb
module User::UserHelper
end

app/views/admin/memorys/edit.html.erb
<h1>Admin::Memorys#edit</h1>
<p>Find me in app/views/admin/memorys/edit.html.erb</p>

app/views/admin/memorys/index.html.erb
<div class="templeheader" style="background-color: moccasin; width: 100%; margin: 0 auto; margin-bottom: 5px;">
  <ul class="nav nav-pills justify-content-center" >
    <li class="nav-item">
      <%= link_to  admin_temples_path, class: "nav-link" do %>
        <i class="fas fa-torii-gate"><span style="margin-left: 5px;">寺・神社</span></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to  admin_memorys_path, class: "nav-link active" do %>
        <i class="fas fa-feather-alt"><span style="margin-left: 5px;">参拝記録</span></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to  admin_questions_path, class: "nav-link" do %>
        <i class="fas fa-question-circle"><span style="margin-left: 5px;">質問</span></i>
      <% end %>
    </li>
  </ul>
</div>

<div class="navheader" style="margin: 0 auto; background-color: moccasin; width: 100%;">
  <ul class="nav nav-pills justify-content-center" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-ranking-tab" data-toggle="pill" href="#pills-ranking" role="tab" aria-controls="pills-ranking"   aria-selected="true">
        <i class="fas fa-crown"><span style="margin-left: 5px;">週間いいねランキング</span></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-new-tab" data-toggle="pill" href="#pills-new" role="tab" aria-controls="pills-new" aria-selected="false">最新の投稿
      </a>
    </li>
  </ul>
</div>

<div class="tab-content" id="pills-tabContent" style="margin-top : 170px;">
  <div class="tab-pane fade show active" id="pills-ranking" role="tabpanel" aria-labelledby="pills-ranking-tab" style="margin-top: 20px;">
    <% @all_ranks.each.with_index(1) do |memory, i| %>
      <div class="row" style="margin-top: 50px;">
        <div class="col-lg-7" style="margin: 0 auto;">
          <i class="fas fa-award" style="color: gold; font-size: 40px;">
            <span style="color: black; font-size: 25px; margin-left: 5px;"><%= "#{i}" %>位</span>
            <span style="font-size: 22px;  color: white; background-color:#8b0000; text-align: center;">
                  週間いいね数：<%= memory.favorites.count %>
            </span>
          </i>
          <div class="well" style="margin-top: 30px; border: solid 1px #8b0000; padding: 10px;">
            <div style="border-bottom: dashed 1px lightgray; ">
              <%= link_to admin_user_path(memory.user) ,:style=>"color:#8b0000;" do %>
                <%= attachment_image_tag memory.user, :profile_image, :fill, 50, 50, format: 'jpeg',style: "border-radius: 50%;", fallback: "no_image.jpg" %>
                <strong style="margin:10px,0,0,6px; font-size: 20px;"><%= memory.user.name %></strong>さん<br>
              <% end %>
              <p style="margin-bottom: 0px;">投稿日：<%= memory.created_at.strftime("%Y-%m-%d %H:%M") %>
                <i class="fa fa-heart" aria-hidden="true" style="color: #e83b69; font-size: 20px; margin-left: 30px;"></i>
                <strong style="color: #e83b69; font-size: 20px; margin-left: 5px;"><%= memory.favorites.count %></strong>
              </p>
            </div>
            <h3 style="width: 350px;  margin-top: 10px;">
              <%= link_to admin_temple_path(memory.temple) ,:style=>"color:#8b0000;" do %>
                <%= memory.temple.name %>(<%= memory.temple.prefecture.name %>)
              <% end %>
            </h3>
            <strong style="font-size: 20px; border-bottom: solid 1px black;"><%= memory.title %></strong><br>
            <p style="font-size: 15px;">訪問日：<%= memory.visit_date %></p><br>
            <div style="margin: 0; width: 600px;">
              <%= simple_format(memory.body) %><br>
            </div>
            <% memory.memory_images.each do |image| %>
              <%= attachment_image_tag image, :image, :fill, 150, 150, format: 'jpeg' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="tab-pane fade" id="pills-new" role="tabpanel" aria-labelledby="pills-new-tab">
    <% @memorys.each do |memory| %>
      <div class="row" style="margin-top: 50px;">
        <div class="col-lg-7" style="margin: 0 auto;">
          <div class="well" style="margin-top: 30px; border: solid 1px #8b0000; padding: 10px;">
            <div style="border-bottom: dashed 1px lightgray; ">
              <%= link_to admin_user_path(memory.user) ,:style=>"color:#8b0000;" do %>
                <%= attachment_image_tag memory.user, :profile_image, :fill, 50, 50, format: 'jpeg',style: "border-radius: 50%;", fallback: "no_image.jpg" %>
                <strong style="margin:10px,0,0,6px; font-size: 20px;"><%= memory.user.name %></strong>さん<br>
              <% end %>
              <p style="margin-bottom: 0px;">投稿日：<%= memory.created_at.strftime("%Y-%m-%d %H:%M") %>
                <i class="fa fa-heart" aria-hidden="true" style="color: #e83b69; font-size: 20px; margin-left: 30px;"></i>
                <strong style="color: #e83b69; font-size: 20px; margin-left: 5px;"><%= memory.favorites.count %></strong>
              </p>
            </div>
            <h3 style="width: 350px;  margin-top: 10px;">
              <%= link_to admin_temple_path(memory.temple) ,:style=>"color:#8b0000;" do %>
                <%= memory.temple.name %>(<%= memory.temple.prefecture.name %>)
              <% end %>
            </h3>
            <strong style="font-size: 20px; border-bottom: solid 1px black;"><%= memory.title %></strong><br>
            <p style="font-size: 15px;">訪問日：<%= memory.visit_date %></p><br>
            <div style="margin: 0; width: 600px;">
              <%= simple_format(memory.body) %><br>
            </div>
            <% memory.memory_images.each do |image| %>
              <%= attachment_image_tag image, :image, :fill, 150, 150, format: 'jpeg' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div style="margin-left: 650px; margin-top: 20px; color:#8b0000; ">
      <%= paginate @memorys %>
    </div>
  </div>
</div>