config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'user/temples#index'

   namespace :admin do
     resources :temples, only: [:index, :show, :new, :edit, :update, :destroy, :create]
     get 'search', to: 'temples#search'
     get 'searchform', to: 'temples#searchform'
     resources :users, only: [:index, :show, :edit, :update, :destroy]
     resources :memorys, only: [:index, :show, :destroy]
     resources :contacts, only: [:index, :show, :update]
     resources :questions, only: [ :index,:show, :destroy] do
       resource :answers, only: [:destroy]
     end
   end
  namespace :user do
    get 'search', to: 'temples#search'
    get 'searchform', to: 'temples#searchform'
    resources :temples, only: [:index, :show, :edit, :update, :destroy] do
      resource :clips, only: [:create, :destroy]
    end
    resources :users, only: [:show, :new, :edit, :update, :destroy, :create]
    get 'top', to: 'users#top'
    resources :contacts, only: [ :new, :create]
    get 'top', to: 'users#top'
      get 'memorys/:id/new' => 'memorys#new', as: 'new_memory'
    post 'memorys/:id/create' => 'memorys#create', as: 'create_memory'
    resources :memorys, only: [:index, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :questions, only: [ :index,:show, :destroy, :create] do
      resource :answers, only: [ :new, :create,:destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum gender: [ :'男性', :'女性' ]
  enum age: [ :'10代', :'20代', :'30代', :'40代', :'50代', :'60代以上' ]

  has_many :memorys, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :clips, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  attachment :profile_image
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_admin!
  PER = 10

  def index
  	@users = User.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @clips = Clip.where(user_id: @user.id).page(params[:page]).per(PER)
    @memorys = @user.memorys.page(params[:page]).per(10)
    @questions = @user.questions.page(params[:page]).per(PER).order(created_at: "DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :gender, :age, :name, :profile_image, :prefecture_id)
  end
end

app/controllers/user/answers_controller.rb
class User::AnswersController < ApplicationController
  def new
  	@question = Question.find(params[:question_id])
  	@answer = Answer.new
  	@user = current_user
  end

  def create
  	question = Question.find(params[:question_id])
    answer = current_user.answers.new(answer_params)
    answer.question_id = question.id
    answer.save
    redirect_to user_questions_path
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to user_question_path(@answer.question)
  end

  def answer_params
  	params.require(:answer).permit(:user_id, :body, :question_id)
  end
end

app/controllers/user/clips_controller.rb
class User::ClipsController < ApplicationController
def create
  	temple = Temple.find(params[:temple_id])
    clip = current_user.clips.new(temple_id: temple.id)
    clip.save
    redirect_back(fallback_location: user_temples_path)
  end

  def destroy
  	temple = Temple.find(params[:temple_id])
    clip = current_user.clips.find_by(temple_id: temple.id)
    clip.destroy
    redirect_back(fallback_location: user_temples_path)
  end


end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  def new
  	@contact = Contact.new
    @user = current_user
  end

  def create
    @user = current_user
  	@contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
      if @contact.save
  	    flash[:notice] = "お問い合わせを承りました。回答につきましては、メールにてご連絡致します。"
  	    redirect_to user_user_path(@user)
      else
        render :new
      end
  end

private

  def contact_params
  	params.require(:contact).permit(:user_id, :contact)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
  	memory = Memory.find(params[:memory_id])
    favorite = current_user.favorites.new(memory_id: memory.id)
    favorite.save
    redirect_back(fallback_location: user_temples_path)
  end

  def destroy
  	memory = Memory.find(params[:memory_id])
    favorite = current_user.favorites.find_by(memory_id: memory.id)
    favorite.destroy
    redirect_back(fallback_location: user_temples_path)
  end

end

app/controllers/user/memorys_controller.rb
class User::MemorysController < ApplicationController
  PER = 10
  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Memory.find(Favorite.where(created_at: from...to).group(:memory_id).order('count(memory_id) desc').limit(10).pluck(:memory_id))
    @memorys = Memory.page(params[:page]).per(PER).order(created_at: "DESC")
  end

  def new
    @temple = Temple.find(params[:id])
  	@memory = Memory.new
    @memory.memory_images.build
  end

  def create
  	@temple = Temple.find(params[:id])
  	@memory = @temple.memorys.build(memory_params)
  	@memory.user_id = current_user.id
  	if
      @memory.save!
      redirect_to user_temple_path(@temple)
    else
      render :new
    end
  end

  def edit
    @memory = Memory.find(params[:id])
  end

  def update
    @memory = Memory.find(params[:id])
    if @memory.update(memory_params)
       flash[:notice] = "memoryを更新しました"
       redirect_to user_user_path(current_user.id)
    else
       render :edit
    end
  end

  def destroy
      @memory = Memory.find(params[:id])
      @memory.destroy
      redirect_to user_user_path(current_user.id)
  end

   private

  def memory_params
    params.require(:memory).permit(:user_id, :temple_id, :title, :body, :visit_date, memory_images_images: [])
  end
end

app/controllers/user/questions_controller.rb
class User::QuestionsController < ApplicationController
  impressionist :actions=> [:show]
  PER = 10

  def index
  	@question = Question.new
  	@questions = Question.page(params[:page]).per(PER).order(created_at: "DESC").search(params[:search])
    @most_viewed = Question.order('impressions_count DESC').take(10)
    @user = current_user
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.page(params[:page]).per(PER).order(created_at: "DESC")
    impressionist(@question, nil, unique: [:session_hash])
  end
   def create
  	@user = current_user
  	@question = Question.new(question_params)
    @question.user_id = current_user.id
      if @question.save
  	    redirect_to user_questions_path
      else
        render :index
      end
  end
  def destroy
      @question = Question.find(params[:id])
      @question.destroy
      redirect_to user_questions_path
  end

  private

  def question_params
  	params.require(:question).permit(:user_id, :body)
  end
end

app/controllers/user/temples_controller.rb
class User::TemplesController < ApplicationController
  PER = 15

  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Temple.find(Clip.where(created_at: from...to).group(:temple_id).order('count(temple_id) desc').limit(10).pluck(:temple_id))
    @hokkaidous = Temple.where("area = 1").page(params[:page]).per(PER)
    @touhokus = Temple.where("area = 2").page(params[:page]).per(PER)
    @kantous = Temple.where("area = 3").page(params[:page]).per(PER)
    @tyubus = Temple.where("area = 4").page(params[:page]).per(PER)
    @kinkis = Temple.where("area = 5").page(params[:page]).per(PER)
    @tyugokus = Temple.where("area = 6").page(params[:page]).per(PER)
    @sikokus = Temple.where("area = 7").page(params[:page]).per(PER)
    @kyusyus = Temple.where("area = 8").page(params[:page]).per(PER)
  end

  def show
  	@temple = Temple.find(params[:id])
  	@user = current_user
    @memorys = @temple.memorys.page(params[:page]).per(10).order(created_at: "DESC")
  end

  def edit
    @temple = Temple.find(params[:id])
  end

  def search
    @q = Temple.search(search_params)
    @temples = @q.result(distinct: true).page(params[:page]).per(15).order(created_at: "DESC")
  end

  def searchform
    @q = Temple.ransack(params[:q])
    @temples = @q.result(distinct: true)
    @goriyakus = Goriyaku.all
    @prefectures = Prefecture.all
  end


  def complete
  end


   private
  def search_params
    params.require(:q).permit!
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  PER = 10
  def show
    @user = User.find(params[:id])
    @clips = Clip.where(user_id: @user.id).all
    @memorys = @user.memorys.page(params[:page]).per(PER).order(created_at: "DESC")
    @questions = @user.questions.page(params[:page]).per(PER).order(created_at: "DESC")
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :gender, :age, :name, :profile_image, :prefecture_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
      user_temples_path
  end

  def after_sign_out_path_for(resource)
      new_user_session_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/answers_helper.rb
module User::AnswersHelper
end

app/helpers/user/clips_helper.rb
module User::ClipsHelper
end

app/helpers/user/contacts_helper.rb
module User::ContactsHelper
end

app/views/user/users/edit.html.erb
<div class="templeheader" style="background-color: moccasin; width: 100%; margin: 0 auto; margin-bottom: 5px;">
    <ul class="nav nav-pills justify-content-center" >
      <li class="nav-item">
        <%= link_to  user_temples_path, class: "nav-link" do %>
          <i class="fas fa-torii-gate"><span style="margin-left: 5px;">寺・神社</span></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  user_memorys_path, class: "nav-link" do %>
          <i class="fas fa-feather-alt"><span style="margin-left: 5px;">参拝記録</span></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  user_questions_path, class: "nav-link" do %>
          <i class="fas fa-question-circle"><span style="margin-left: 5px;">質問</span></i>
        <% end %>
      </li>
    </ul>
</div>

<div class="row" style="margin-top: 140px;">
  <div class="col-lg-7" style="margin: 0 auto; text-align: center;">

    <h2 style="border-bottom: solid 2px #8b0000"> ユーザー情報の編集</h2>

    <%= form_for(@user, :url => {:controller => :users, :action => :update}) do |f| %>

      <div style="margin-top: 30px;">
        <h3>ユーザー名</h3>
        <%= f.text_field :name, autofocus: true, placeholder: "ユーザー名" %>
      </div>

      <div style="margin-top: 30px;">
        <h3>写真</h3>
        <%= f.attachment_field :profile_image %>
      </div>

      <div style="margin-top: 30px;">
        <h3>メールアドレス</h3>
        <%= f.email_field :email, autofocus: true, placeholder: "メールアドレス" %>
      </div>

      <div style="margin-top: 30px;">
        <h3>年齢</h3>
        <%= f.select :age, User.ages.keys, {},  :prompt => "選択してください" %>
      </div>

      <div style="margin-top: 30px;">
        <h3>性別</h3>
        <%= f.select :gender, User.genders.keys, {}, :prompt => "選択してください" %>
      </div>

      <div style="margin-top: 40px;">
        <%= f.submit '変更' ,:style => "background-color:yellowgreen;" %>
      </div>

    <% end %>

  </div>
</div>

app/views/user/users/show.html.erb
<div class="templeheader" style="background-color: moccasin; width: 100%; margin: 0 auto; margin-bottom: 5px;">
    <ul class="nav nav-pills justify-content-center" >
       <li class="nav-item">
        <%= link_to  user_temples_path, class: "nav-link" do %>
          <i class="fas fa-torii-gate"><span style="margin-left: 5px;">寺・神社</span></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  user_memorys_path, class: "nav-link" do %>
          <i class="fas fa-feather-alt"><span style="margin-left: 5px;">参拝記録</span></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  user_questions_path, class: "nav-link" do %>
          <i class="fas fa-question-circle"><span style="margin-left: 5px;">質問</span></i>
        <% end %>
      </li>
    </ul>
</div>

<div class="row align-items-start" style="margin-top : 140px; margin-bottom: 30px;">

  <div class="col-md-4" style="margin: 40px 50px 0 30px; background: #660000; padding: 20px; border: none; border-radius: 30px;">
    <div class="clearfix" style="border-bottom: dashed 1px white; padding-bottom: 20px;">
      <div style="float: left; margin-top: 20px;">
        <%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: 'jpeg', fallback: "no_image.jpg" ,style: "border-radius: 50%;" %>
      </div>
      <div  class="profilelist" style="margin-top: 20px;">
        <p class="username" style="color: white;">
          <strong style="margin:10px,0,0,6px; font-size: 25px;"><%= @user.name %></strong>さん
        </p>
        <p style="font-size: 20px; color: white;">投稿数：<%= @user.memorys.count %></p><br>
        <% if @user == current_user %>
          <%= link_to "ユーザー情報編集", edit_user_user_path, class: "btn btn col-md-12 col-md-1",style: "background-color:yellowgreen; color:black;" %>
        <% end %>
      </div>
    </div>
    <div class="clearfix" style="border-bottom: dashed 1px white; padding-bottom: 20px; margin-top: 20px;">
      <h3 style="margin-bottom: 20px; color: white;  width: 400px; "><i class="far fa-star">お気に入り</i></h3>
      <% @clips.each do |clip| %>
        <%= link_to user_temple_path(clip.temple) ,:style=>"color:white;" do %>
          <div id="box" style="margin-left: 40px; margin-bottom: 20px; width: 160px; float: left;">
            <table class="clip-box">
              <tr>
                <td>
                  <%= clip.temple.name %>(<%= clip.temple.prefecture.name %>)
                </td>
              </tr>
              <tr>
                <td>
                  <%= attachment_image_tag clip.temple, :mainimage, :fill, 100, 100, format: 'jpeg',style: "border-radius: 50%; margin-top:10px;" %>
                </td>
              </tr>
            </table>
          </div>
        <% end %>
      <% end %>
    </div>
    <div style="margin-top: 20px; color: white;">
      <h3 style="margin: 0 auto; color: white;"><i class="fas fa-history">質問</i></h3>
          <table class="table table-hover" style="margin-top: 20px;">
            <% @questions.each do |question| %>
              <tr>
                <td style="width:100px;">
                    <%= attachment_image_tag question.user, :profile_image, :fill, 50, 50, format: 'jpeg',style: "border-radius: 50%;" %>
                </td>
                <td><%= simple_format(question.body) %></td>
                <td>
                  <%= link_to new_user_question_answers_path(question),:style=>"color:yellowgreen;" do %>
                  <i class="fas fa-reply"></i>
                  <% end %>
                </td>
                <td>
                  <%= link_to user_question_path(question),:style=>"color:black;" do %>
                  <i class="far fa-comment-alt" style="color: white;"><strong style="margin-left: 5px;"><%= question.answers.count %></strong></i>
                  <% end %>
                </td>
                <td><%= question.created_at.strftime("%Y-%m-%d %H:%M") %></td>
              </tr>
            <% end %>
          </table>
          <%= paginate @questions %>
    </div>
  </div>

  <div class="col-lg-7" style="margin-top:40px; margin-left: 10px; " >
    <h2 style="border-bottom: solid 3px #8b0000; text-align: center;">
      <strong style="font-size: 35px;"><%= @user.name %></strong>さんの<strong style="font-size: 35px;">投稿一覧</strong>
    </h2>
    <% @memorys.each do |memory| %>
      <div class="well" style="margin-top: 30px; border: solid 1px #8b0000; padding: 10px; border-radius: 30px;">
        <div style="border-bottom: dashed 1px lightgray; ">
          <%= link_to user_user_path(memory.user) ,:style=>"color:#8b0000;" do %>
            <%= attachment_image_tag memory.user, :profile_image, :fill, 50, 50, format: 'jpeg',style: "border-radius: 50%;", fallback: "no_image.jpg" %>
            <strong style="margin:10px,0,0,6px; font-size: 20px;"><%= memory.user.name %></strong>さん<br>
          <% end %>
          <p style="margin-bottom: 0px;">投稿日：<%= memory.created_at.strftime("%Y-%m-%d %H:%M") %>
            <% if memory.favorited_by?(current_user) %>
              <%= link_to user_memory_favorites_path(memory), method: :delete,:style=>"color:#e83b69;" do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: #e83b69; font-size: 20px; margin-left: 30px;"></i>
                <strong style="color: #e83b69; font-size: 20px; margin-left: 5px;"><%= memory.favorites.count %></strong>
              <% end %>
            <% else %>
              <%= link_to user_memory_favorites_path(memory), method: :post,:style=>"color:#e83b69;" do %>
                <i class="far fa-heart" aria-hidden="true" style="font-size: 20px; color: #e83b69; margin-left: 30px;"></i>
                <strong style="color: #e83b69; font-size: 20px; margin-left: 5px;"><%= memory.favorites.count %></strong>
              <% end %>
            <% end %>
            <% if memory.user == current_user %>
              <%= link_to  user_memory_path(memory), method: :delete,"data-confirm" => "削除しますか？",style: "color:#8b0000; margin-left:350px; font-size:20px;" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </p>
        </div>
        <h3 style="width: 400px;  margin-top: 10px;">
          <%= link_to user_temple_path(memory.temple) ,:style=>"color:#8b0000;" do %>
            <%= memory.temple.name %>(<%= memory.temple.prefecture.name %>)
          <% end %>
        </h3>
        <strong style="font-size: 20px; border-bottom: solid 1px black;"><%= memory.title %></strong><br>
        <p style="font-size: 15px;">訪問日：<%= memory.visit_date %></p><br>
        <div style="margin: 0; width: 600px;">
          <%= simple_format(memory.body) %><br>
        </div>
        <% memory.memory_images.each do |image| %>
          <%= attachment_image_tag image, :image, :fill, 150, 150, format: 'jpeg' %>
        <% end %>
      </div>
    <% end %>
    <%= paginate @memorys %>
  </div>
</div>