config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'user/temples#index'

   namespace :admin do
     resources :temples, only: [:index, :show, :new, :edit, :update, :destroy, :create]
     get 'search', to: 'temples#search'
     get 'searchform', to: 'temples#searchform'
     resources :users, only: [:index, :show, :edit, :update, :destroy]
     resources :memorys, only: [:index, :show, :destroy]
     resources :contacts, only: [:index, :show, :update]
     resources :questions, only: [ :index,:show, :destroy] do
       resource :answers, only: [:destroy]
     end
   end
  namespace :user do
    get 'search', to: 'temples#search'
    get 'searchform', to: 'temples#searchform'
    resources :temples, only: [:index, :show, :edit, :update, :destroy] do
      resource :clips, only: [:create, :destroy]
    end
    resources :users, only: [:show, :new, :edit, :update, :destroy, :create]
    get 'top', to: 'users#top'
    resources :contacts, only: [ :new, :create]
    get 'top', to: 'users#top'
      get 'memorys/:id/new' => 'memorys#new', as: 'new_memory'
    post 'memorys/:id/create' => 'memorys#create', as: 'create_memory'
    resources :memorys, only: [:index, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :questions, only: [ :index,:show, :destroy, :create] do
      resource :answers, only: [ :new, :create,:destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/temple.rb
class Temple < ApplicationRecord

	has_many :memorys, dependent: :destroy
	belongs_to :prefecture
	belongs_to :goriyaku
	attachment :mainimage
	has_many :clips, dependent: :destroy
        def cliped_by?(user)
          clips.where(user_id: user.id).exists?
        end
    has_many :temple_images, dependent: :destroy
 	 accepts_attachments_for :temple_images, attachment: :image

	validates :prefecture_id, presence: true
	validates :goriyaku_id, presence: true

	after_validation :geocode

	  private
	  def geocode
	    uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=AIzaSyDV7aHnCQ6Lbws5KlkFCA7XzgB4So2mREE")
	    res = HTTP.get(uri).to_s
	    response = JSON.parse(res)
	    self.latitude = response["results"][0]["geometry"]["location"]["lat"]
	    self.longitude = response["results"][0]["geometry"]["location"]["lng"]
	  end


  	enum area: { 北海道: 1, 東北: 2, 関東: 3, 中部: 4, 近畿: 5,中国: 6, 四国: 7, 九州沖縄:8 }
end

app/controllers/admin/temples_controller.rb
class Admin::TemplesController < ApplicationController
    before_action :authenticate_admin!
     PER = 15
  def new
  	@temple = Temple.new
    @temple.temple_images.build
  end

  def create
  	@temple = Temple.new(temple_params)
  	if
      @temple.save!
      redirect_to user_temples_path
    else
      render :new
    end
  end

  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Temple.find(Clip.where(created_at: from...to).group(:temple_id).order('count(temple_id) desc').limit(10).pluck(:temple_id))
    @hokkaidous = Temple.where("area = 1").page(params[:page]).per(PER)
    @touhokus = Temple.where("area = 2").page(params[:page]).per(PER)
    @kantous = Temple.where("area = 3").page(params[:page]).per(PER)
    @tyubus = Temple.where("area = 4").page(params[:page]).per(PER)
    @kinkis = Temple.where("area = 5").page(params[:page]).per(PER)
    @tyugokus = Temple.where("area = 6").page(params[:page]).per(PER)
    @sikokus = Temple.where("area = 7").page(params[:page]).per(PER)
    @kyusyus = Temple.where("area = 8").page(params[:page]).per(PER)
  end

  def show
    @temple = Temple.find(params[:id])
    @user = current_user
    @memorys = @temple.memorys.page(params[:page]).per(10).order(created_at: "DESC")
  end

  def create
    @temple = Temple.new(temple_params)
    if
      @temple.save!
      redirect_to admin_temples_path
    else
      render :new
    end
  end

  def edit
    @temple = Temple.find(params[:id])
    @temple.temple_images.build
  end

  def update
    @temple = Temple.find(params[:id])
    if @temple.update(temple_params)
       flash[:notice] = "更新しました"
       redirect_to admin_temple_path(@temple)
    else
       render :edit
    end
  end

  def destroy
      @temple = Temple.find(params[:id])
      @temple.destroy
      redirect_to admin_temples_path
  end

  def search
    @q = Temple.search(search_params)
    @temples = @q.result(distinct: true).page(params[:page]).per(10).order(created_at: "DESC")
  end

  def searchform
    @q = Temple.ransack(params[:q])
    @temples = @q.result(distinct: true)
    @goriyakus = Goriyaku.all
    @prefectures = Prefecture.all
  end

  private

  def temple_params
    params.require(:temple).permit(:name, :area, :address, :mainimage, :prefecture_id, :goriyaku_id, :latitude, :longitude, temple_images_images: [])
  end

  def search_params
    params.require(:q).permit!
  end
end

app/controllers/user/temples_controller.rb
class User::TemplesController < ApplicationController
  PER = 15

  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Temple.find(Clip.where(created_at: from...to).group(:temple_id).order('count(temple_id) desc').limit(10).pluck(:temple_id))
    @hokkaidous = Temple.where("area = 1").page(params[:page]).per(PER)
    @touhokus = Temple.where("area = 2").page(params[:page]).per(PER)
    @kantous = Temple.where("area = 3").page(params[:page]).per(PER)
    @tyubus = Temple.where("area = 4").page(params[:page]).per(PER)
    @kinkis = Temple.where("area = 5").page(params[:page]).per(PER)
    @tyugokus = Temple.where("area = 6").page(params[:page]).per(PER)
    @sikokus = Temple.where("area = 7").page(params[:page]).per(PER)
    @kyusyus = Temple.where("area = 8").page(params[:page]).per(PER)
  end

  def show
  	@temple = Temple.find(params[:id])
  	@user = current_user
    @memorys = @temple.memorys.page(params[:page]).per(10).order(created_at: "DESC")
  end

  def edit
    @temple = Temple.find(params[:id])
  end

  def search
    @q = Temple.search(search_params)
    @temples = @q.result(distinct: true).page(params[:page]).per(15).order(created_at: "DESC")
  end

  def searchform
    @q = Temple.ransack(params[:q])
    @temples = @q.result(distinct: true)
    @goriyakus = Goriyaku.all
    @prefectures = Prefecture.all
  end


  def complete
  end


   private
  def search_params
    params.require(:q).permit!
  end
end

app/helpers/admin/temples_helper.rb
module Admin::TemplesHelper
end

app/helpers/user/temples_helper.rb
module User::TemplesHelper
end

app/views/admin/temples/edit.html.erb
<div style="margin-top: 140px; text-align: center;">
  <h1 style="color: #8b0000"> 寺・神社情報編集</h1>
  <%= form_for(@temple, :url => {:controller => :temples, :action => :update}) do |f| %>
    <div>
      <h3 style="margin-top: 20px;">寺・神社名</h3>
      <%= f.text_field :name %>
    </div>
    <div>
      <h3 style="margin-top: 20px;">メイン写真</h3>
      <%= f.attachment_field :mainimage %><br>
      <%= attachment_image_tag  @temple, :mainimage, :fill, 100, 100, format: 'jpeg' %>
    </div>
    <div style="margin-top: 20px;">
      <h3>その他写真</h3>
      <%= f.attachment_field :temple_images_images, multiple: true %><br>
      <% @temple.temple_images.each do |image| %>
        <%= attachment_image_tag image, :image, :fill, 100, 70, format: 'jpeg' %>
      <% end %>
    </div>
    <div style="margin-top: 20px;">
      <h3>エリア</h3>
      <%= f.select :area, Temple.areas.keys, class: "select-default" %>
    </div>
    <div style="margin-top: 20px;">
      <h3>都道府県</h3>
      <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name %>
    </div>
    <div style="margin-top: 20px;">
      <h3>場所</h3>
      <%= f.text_field :address %>
    </div>
    <div style="margin-top: 20px;">
      <h3>ご利益</h3>
      <%= f.collection_select :goriyaku_id, Goriyaku.all, :id, :name %>
    </div>
    <div style="margin-top: 20px;">
      <%= f.submit '更新' %>
    </div>
  <% end %>
</div>

app/views/admin/temples/index.html.erb
<div class="templeheader" style="background-color: moccasin; width: 100%; margin: 0 auto; margin-bottom: 5px;">
    <ul class="nav nav-pills justify-content-center" >
      <li class="nav-item">
        <%= link_to  admin_temples_path, class: "nav-link active" do %>
          <i class="fas fa-torii-gate"><span style="margin-left: 5px;">寺・神社</span></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  admin_memorys_path, class: "nav-link" do %>
          <i class="fas fa-feather-alt"><span style="margin-left: 5px;">参拝記録</span></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  admin_questions_path, class: "nav-link" do %>
          <i class="fas fa-question-circle"><span style="margin-left: 5px;">質問</span></i>
        <% end %>
      </li>
    </ul>
</div>

<div class="navheader" style="margin: 0 auto; background-color: moccasin; width: 100%;">
    <ul class="nav nav-pills justify-content-center" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="pills-ranking-tab" data-toggle="pill" href="#pills-ranking" role="tab" aria-controls="pills-ranking" aria-selected="true"><i class="fas fa-crown"><span style="margin-left: 5px;">週間お気に入りランキング</span></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-hokkaidou-tab" data-toggle="pill" href="#pills-hokkaidou" role="tab" aria-controls="pills-hollaidou" aria-selected="false">北海道</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-touhoku-tab" data-toggle="pill" href="#pills-touhoku" role="tab" aria-controls="pills-touhoku" aria-selected="false">東北</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-kantou-tab" data-toggle="pill" href="#pills-kantou" role="tab" aria-controls="pills-kantou" aria-selected="false">関東</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-tyubu-tab" data-toggle="pill" href="#pills-tyubu" role="tab" aria-controls="pills-tyubu" aria-selected="false">中部</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-kinki-tab" data-toggle="pill" href="#pills-kinki" role="tab" aria-controls="pills-kinki" aria-selected="false">近畿</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-tyugoku-tab" data-toggle="pill" href="#pills-tyugoku" role="tab" aria-controls="pills-tyugoku" aria-selected="false">中国</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-sikoku-tab" data-toggle="pill" href="#pills-sikoku" role="tab" aria-controls="pills-sikoku" aria-selected="false">四国</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-kyusyu-tab" data-toggle="pill" href="#pills-kyusyu" role="tab" aria-controls="pills-kyusyu" aria-selected="false">九州・沖縄</a>
      </li>
    </ul>
</div>

<!-- パネル部分 -->
<div class="tab-content" id="pills-tabContent" style="margin-top : 170px;">

    <div class="tab-pane fade show active" id="pills-ranking" role="tabpanel" aria-labelledby="pills-ranking-tab" style="margin-top: 20px;">
      <div class="row" style="margin-top: 120px;">
        <div class="col-lg-2">
          <% @all_ranks.each.with_index(1) do |temple,i| %>
          <p style="margin-bottom: 245px; margin-left: 250px; font-size: 35px; ">
            <i class="fas fa-award" style="color: gold;"><span style="color: black; font-size: 25px; margin-left: 5px;"><%= "#{i}" %></span></i>
          </p><br>
          <% end %>

        </div>

        <div class="col-lg-4">
          <% @all_ranks.each do |temple| %>
            <div style="font-size: 22px; width: 200px; color: white; background-color:#8b0000; text-align: center;margin-left: 150px; margin-bottom: 265px;">
                <%= temple.clips.count %><br>
                <p style="font-size: 15px;">週間お気に入り追加数</p>
            </div>
          <% end %>
        </div>

        <div class="col-lg-6">
          <% @all_ranks.each do |temple| %>
            <div class="templeranks">
              <%= link_to admin_temple_path(temple)  do %>
                <%= attachment_image_tag temple, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %><br>
                <p><%= temple.name %></p>
                <h4>(<%= temple.prefecture.name %>)</h4>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-hokkaidou" role="tabpanel" aria-labelledby="pills-hokkaidou-tab">
        <div class="clearfix">
          <% @hokkaidous.each do |hokkaidou| %>
          <div class="temples">
            <%= link_to admin_temple_path(hokkaidou)  do %>
              <%= attachment_image_tag hokkaidou, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
              <p><%= hokkaidou.name %></p>
              <h4>(<%= hokkaidou.prefecture.name %>)</h4>
            <% end %>
          </div>
          <% end %>
        </div>
        <div style="margin: 0 auto; width: 18%;">
         <%= paginate @hokkaidous %>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-touhoku" role="tabpanel" aria-labelledby="pills-touhoku-tab">
        <div class="clearfix">
          <% @touhokus.each do |touhoku| %>
          <div class="temples">
            <%= link_to admin_temple_path(touhoku)  do %>
              <%= attachment_image_tag touhoku, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
              <p><%= touhoku.name %></p>
              <h4>(<%= touhoku.prefecture.name %>)</h4>
            <% end %>
          </div>
          <% end %>
        </div>
        <div style="margin: 0 auto; width: 18%;">
         <%= paginate @touhokus %>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-kantou" role="tabpanel" aria-labelledby="pills-kantou-tab">
        <div class="clearfix">
          <% @kantous.each do |kantou| %>
                  <div class="temples">
                    <%= link_to admin_temple_path(kantou)  do %>
                      <%= attachment_image_tag kantou, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
                      <p><%= kantou.name %></p>
                      <h4>(<%= kantou.prefecture.name %>)</h4>
                    <% end %>
                  </div>
          <% end %>
        </div>
        <div style="margin: 0 auto; width: 18%;">
         <%= paginate @kantous %>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-tyubu" role="tabpanel" aria-labelledby="pills-tyubu-tab">
        <div class="clearfix">
          <% @tyubus.each do |tyubu| %>
          <div class="temples">
            <%= link_to admin_temple_path(tyubu)  do %>
              <%= attachment_image_tag tyubu, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
              <p><%= tyubu.name %></p>
              <h4>(<%= tyubu.prefecture.name %>)</h4>
            <% end %>
              </div>
          <% end %>
        </div>
        <div style="margin: 0 auto; width: 18%;">
         <%= paginate @tyubus %>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-kinki" role="tabpanel" aria-labelledby="pills-kinki-tab">
        <div class="clearfix">
          <% @kinkis.each do |kinki| %>
          <div class="temples">
            <%= link_to admin_temple_path(kinki)  do %>
              <%= attachment_image_tag kinki, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
              <p><%= kinki.name %></p>
              <h4>(<%= kinki.prefecture.name %>)</h4>
            <% end %>
              </div>
          <% end %>
        </div>
        <div style="margin: 0 auto; width: 18%;">
         <%= paginate @kinkis %>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-tyugoku" role="tabpanel" aria-labelledby="pills-tyugoku-tab">
        <div class="clearfix">
          <% @tyugokus.each do |tyugoku| %>
          <div class="temples">
            <%= link_to admin_temple_path(tyugoku)  do %>
              <%= attachment_image_tag tyugoku, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
              <p><%= tyugoku.name %></p>
              <h4>(<%= tyugoku.prefecture.name %>)</h4>
            <% end %>
              </div>
          <% end %>
        </div>
        <div style="margin: 0 auto; width: 18%;">
         <%= paginate @tyugokus %>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-sikoku" role="tabpanel" aria-labelledby="pills-sikoku-tab">
        <div class="clearfix">
          <% @sikokus.each do |sikoku| %>
          <div class="temples">
            <%= link_to admin_temple_path(sikoku)  do %>
              <%= attachment_image_tag sikoku, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
              <p><%= sikoku.name %></p>
              <h4>(<%= sikoku.prefecture.name %>)</h4>
            <% end %>
              </div>
          <% end %>
        </div>
        <div style="margin: 0 auto; width: 18%;">
         <%= paginate @sikokus %>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-kyusyu" role="tabpanel" aria-labelledby="pills-kyusyu-tab">
        <div class="clearfix">
          <% @kyusyus.each do |kyusyu| %>
          <div class="temples">
            <%= link_to admin_temple_path(kyusyu)  do %>
              <%= attachment_image_tag kyusyu, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
              <p><%= kyusyu.name %></p>
              <h4>(<%= kyusyu.prefecture.name %>)</h4>
            <% end %>
              </div>
          <% end %>
        </div>
        <div style="margin: 0 auto; width: 18%;">
         <%= paginate @kyusyus %>
        </div>
    </div>
</div>

app/views/admin/temples/new.html.erb
<div class="raw" style="margin-top: 140px;">
	<div class="col-md-6" style="margin: 0 auto; text-align: center;">
		<h1 style="border-bottom: solid 2px #8b0000"> 寺・神社新規投稿</h1>
		<div style="margin-top: 20px;">
			<%= form_for(@temple, :url => {:controller => :temples, :action => :create}) do |f| %>
				<div style="margin-top: 20px;">
					<h3>寺・神社名</h3>
					<%= f.text_field :name %>
				</div>
				<div style="margin-top: 20px;">
					<h3>メイン写真</h3>
					<%= f.attachment_field :mainimage %>
				</div>
				<div style="margin-top: 20px;">
					<h3>その他写真</h3>
					<%= f.attachment_field :temple_images_images, multiple: true %>
				</div>
				<div style="margin-top: 20px;">
					<h3>エリア</h3>
					<%= f.select :area, Temple.areas.keys, class: "select-default" %>
				</div>
				<div style="margin-top: 20px;">
					<h3>都道府県</h3>
					<%= f.collection_select :prefecture_id, Prefecture.all, :id, :name %>
				</div>
				<div style="margin-top: 20px;">
					<h3>場所</h3>
					<%= f.text_field :address %>
				</div>
				<div style="margin-top: 20px;">
					<h3>ご利益</h3>
					<%= f.collection_select :goriyaku_id, Goriyaku.all, :id, :name %>
				</div>
				<div style="margin-top: 20px;">
					<%= f.submit '新規追加' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/temples/search.html.erb
<h1 style="margin-top : 140px; margin-left: 170px;">検索結果</h1>
<div>
	<% @temples.each do |temple| %>
        <div class="temples">
         	<%= link_to admin_temple_path(temple)  do %>
            	<%= attachment_image_tag temple, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
            	<p><%= temple.name %></p>
            	<h4>(<%= temple.prefecture.name %>)</h4>
          <% end %>
        </div>
	<% end %>
	<%= paginate @temples %>
</div>

app/views/admin/temples/searchform.html.erb
<div style="text-align: center; margin-top: 140px;">
  <%= search_form_for(@q, :url => {:controller => :temples, :action => :search}) do |f| %>
    <div style="margin-bottom: 20px;">
      <h2>検索</h2>
    </div>
    <div>
      <%= f.label :name_cont, "寺・神社名" %>
      <%= f.search_field :name_cont %>
    </div>
    <br />
    <div>
      <%= f.label :prefecture_id_eq, "都道府県名" %>
      <%= f.collection_select :prefecture_id_eq, @prefectures, :id, :name, :include_blank => '指定なし'%>
    </div>
    <br />
    <div>
      <%= f.label :goriyaku_id_eq, "ご利益名" %>
      <%= f.collection_select :goriyaku_id_eq, @goriyakus, :id, :name, :include_blank => '指定なし'%>
    </div>
    <br />
    <%= f.submit %>
  <% end %>
</div>

app/views/admin/temples/show.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<div class="row" style="margin-top : 120px;">
	<div class="col-lg-4" style="margin-left: 50px;">
		<div>
			<div style="font-size: 50px; border-bottom: solid 3px #8b0000; text-align: center;">
				<%= @temple.name %><br>
				<%= link_to "編集", edit_admin_temple_path(@temple), class: "btn btn-info col-md-2 col-md-offset-1" %>
				<%= link_to "削除", admin_temple_path(@temple), method: :delete, class: "btn btn-info col-md-2 col-md-offset-1", "data-confirm" => "本当に削除しますか？",:style=>"background-color:red;" %>
			</div>
			<div id="temple-info"><%= @temple.address %></div>
			<div id="temple-info">ご利益：<%= @temple.goriyaku.name %></div>
		</div>
		<div id="map" style='width: 250px; height: 250px;'></div>
			<script type="text/javascript">
				    handler = Gmaps.build('Google');
				    handler.buildMap({ provider: { scrollwheel: false }, internal: {id: 'map'}}, function(){
				      markers = handler.addMarkers([
				        {
				          "lat": <%= @temple.latitude %>,
				          "lng": <%= @temple.longitude %>,
						  "infowindow": '<p><%= @temple.name %></p><p><%= @temple.address %></p><p><%= link_to "Googleマップで見る" ,"https://maps.google.co.jp/maps?q=loc:#{@temple.latitude},#{@temple.longitude}&iwloc=J",target: "_blank" %></p>'
				        }
				      ]);
				      handler.bounds.extendWith(markers);
				      handler.fitMapToBounds();
				      handler.getMap().setZoom(17);
				    });
			</script>
		<div class="col-lg-5" style="margin-left: 50px; margin-top: 50px;">
			<div class="tab-content" id="nav-tabContent" style="text-align: center; ">
				<div class="tab-pane fade show active" id="list-mainimage" role="tabpanel" aria-labelledby="list-home-list">
				    <%= attachment_image_tag @temple, :mainimage, :fill, 576, 420, format: 'jpeg' %>
				</div>
				<% @temple.temple_images.each do |image| %>
					<div class="tab-pane fade" id="list-image-<%=image.id %>" role="tabpanel" aria-labelledby="list-image-list">
					    <%= attachment_image_tag image, :image, :fill, 576, 420, format: 'jpeg' %>
					</div>
				<% end %>
			</div>
		</div>
		<div class="col-lg-2" style="margin-top: 70px;">
			<div class="list-group  text-center" id="list-tab" role="tablist" style="margin-right: 20px;">
				<a class="list-group-item list-group-item-action active"  data-toggle="list" href="#list-mainimage" role="tab" aria-controls="list-mainimage">
				    <%= attachment_image_tag @temple, :mainimage, :fill, 100, 70, format: 'jpeg' %>
				</a>
				<% @temple.temple_images.each do |image| %>
				    <a class="list-group-item list-group-item-action" id="list-image-<%=image.id %>-list" data-toggle="list" href="#list-image-<%=image.id %>" role="tab" aria-controls="list-image">
				      	<%= attachment_image_tag image, :image, :fill, 100, 70, format: 'jpeg' %>
				    </a>
				<% end %>
			</div>
		</div>
	</div>
	<div class="row" style="margin-top: 100px; margin-bottom: 30px;">
		<div class="col-lg-7" style="margin: 0 auto;">
			<h2 style="border-bottom: solid 3px #8b0000; text-align: center;">
				<%= @temple.name %>の投稿一覧
			</h2>
			<% @memorys.each do |memory| %>
				<div class="well" style="margin-top: 30px; border: solid 1px #8b0000; padding: 10px;">
					<div style="border-bottom: dashed 1px lightgray; ">
						<%= link_to admin_user_path(memory.user) ,:style=>"color:#8b0000;" do %>
							<%= attachment_image_tag memory.user, :profile_image, :fill, 50, 50, format: 'jpeg',style: "border-radius: 50%;", fallback: "no_image.jpg" %>
							<strong style="margin:10px,0,0,6px; font-size: 20px;"><%= memory.user.name %></strong>さん<br>
						<% end %>
						<p style="margin-bottom: 0px;">投稿日：<%= memory.created_at.strftime("%Y-%m-%d %H:%M") %>
      						<i class="fa fa-heart" aria-hidden="true" style="color: navy; font-size: 20px; margin-left: 30px;"></i>
      						<strong style="color: black; font-size: 20px; margin-left: 5px;"><%= memory.favorites.count %></strong>
							<%= link_to "削除", admin_memory_path(memory), method: :delete, class: "btn btn-info col-md-1 col-md-offset-1" %>
						</p>
					</div>
					<strong style="font-size: 20px; border-bottom: solid 1px black;"><%= memory.title %></strong><br>
					<p style="font-size: 15px;">訪問日：<%= memory.visit_date %></p><br>
					<div style="margin: 0; width: 600px;">
						<%= simple_format(memory.body) %><br>
					</div>
					<% memory.memory_images.each do |image| %>
						<%= attachment_image_tag image, :image, :fill, 150, 150, format: 'jpeg' %>
					<% end %>
				</div>
			<% end %>
			<%= paginate @memorys %>
		</div>
	</div>
</div>