config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'user/temples#index'

   namespace :admin do
     resources :temples, only: [:index, :show, :new, :edit, :update, :destroy, :create]
     get 'search', to: 'temples#search'
     get 'searchform', to: 'temples#searchform'
     resources :users, only: [:index, :show, :edit, :update, :destroy]
     resources :memorys, only: [:index, :show, :destroy]
     resources :contacts, only: [:index, :show, :update]
     resources :questions, only: [ :index,:show, :destroy] do
       resource :answers, only: [:destroy]
     end
   end
  namespace :user do
    get 'search', to: 'temples#search'
    get 'searchform', to: 'temples#searchform'
    resources :temples, only: [:index, :show, :edit, :update, :destroy] do
      resource :clips, only: [:create, :destroy]
    end
    resources :users, only: [:show, :new, :edit, :update, :destroy, :create]
    get 'top', to: 'users#top'
    resources :contacts, only: [ :new, :create]
    get 'top', to: 'users#top'
      get 'memorys/:id/new' => 'memorys#new', as: 'new_memory'
    post 'memorys/:id/create' => 'memorys#create', as: 'create_memory'
    resources :memorys, only: [:index, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :questions, only: [ :index,:show, :destroy, :create] do
      resource :answers, only: [ :new, :create,:destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/temple.rb
class Temple < ApplicationRecord

	has_many :memorys, dependent: :destroy
	belongs_to :prefecture
	belongs_to :goriyaku
	attachment :mainimage
	has_many :clips, dependent: :destroy
        def cliped_by?(user)
          clips.where(user_id: user.id).exists?
        end
    has_many :temple_images, dependent: :destroy
 	 accepts_attachments_for :temple_images, attachment: :image

	validates :prefecture_id, presence: true
	validates :goriyaku_id, presence: true

	after_validation :geocode

	  private
	  def geocode
	    uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=AIzaSyDV7aHnCQ6Lbws5KlkFCA7XzgB4So2mREE")
	    res = HTTP.get(uri).to_s
	    response = JSON.parse(res)
	    self.latitude = response["results"][0]["geometry"]["location"]["lat"]
	    self.longitude = response["results"][0]["geometry"]["location"]["lng"]
	  end


  	enum area: { 北海道: 1, 東北: 2, 関東: 3, 中部: 4, 近畿: 5,中国: 6, 四国: 7, 九州沖縄:8 }
end

app/controllers/admin/temples_controller.rb
class Admin::TemplesController < ApplicationController
    before_action :authenticate_admin!
     PER = 15
  def new
  	@temple = Temple.new
    @temple.temple_images.build
  end

  def create
  	@temple = Temple.new(temple_params)
  	if
      @temple.save!
      redirect_to user_temples_path
    else
      render :new
    end
  end

  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Temple.find(Clip.where(created_at: from...to).group(:temple_id).order('count(temple_id) desc').limit(10).pluck(:temple_id))
    @hokkaidous = Temple.where("area = 1").page(params[:page]).per(PER)
    @touhokus = Temple.where("area = 2").page(params[:page]).per(PER)
    @kantous = Temple.where("area = 3").page(params[:page]).per(PER)
    @tyubus = Temple.where("area = 4").page(params[:page]).per(PER)
    @kinkis = Temple.where("area = 5").page(params[:page]).per(PER)
    @tyugokus = Temple.where("area = 6").page(params[:page]).per(PER)
    @sikokus = Temple.where("area = 7").page(params[:page]).per(PER)
    @kyusyus = Temple.where("area = 8").page(params[:page]).per(PER)
  end

  def show
    @temple = Temple.find(params[:id])
    @user = current_user
    @memorys = @temple.memorys.page(params[:page]).per(10).order(created_at: "DESC")
  end

  def create
    @temple = Temple.new(temple_params)
    if
      @temple.save!
      redirect_to admin_temples_path
    else
      render :new
    end
  end

  def edit
    @temple = Temple.find(params[:id])
    @temple.temple_images.build
  end

  def update
    @temple = Temple.find(params[:id])
    if @temple.update(temple_params)
       flash[:notice] = "更新しました"
       redirect_to admin_temple_path(@temple)
    else
       render :edit
    end
  end

  def destroy
      @temple = Temple.find(params[:id])
      @temple.destroy
      redirect_to admin_temples_path
  end

  def search
    @q = Temple.search(search_params)
    @temples = @q.result(distinct: true).page(params[:page]).per(10).order(created_at: "DESC")
  end

  def searchform
    @q = Temple.ransack(params[:q])
    @temples = @q.result(distinct: true)
    @goriyakus = Goriyaku.all
    @prefectures = Prefecture.all
  end

  private

  def temple_params
    params.require(:temple).permit(:name, :area, :address, :mainimage, :prefecture_id, :goriyaku_id, :latitude, :longitude, temple_images_images: [])
  end

  def search_params
    params.require(:q).permit!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_admin!
  PER = 10

  def index
  	@users = User.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @clips = Clip.where(user_id: @user.id).page(params[:page]).per(PER)
    @memorys = @user.memorys.page(params[:page]).per(10)
    @questions = @user.questions.page(params[:page]).per(PER).order(created_at: "DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :gender, :age, :name, :profile_image, :prefecture_id)
  end
end

app/controllers/user/answers_controller.rb
class User::AnswersController < ApplicationController
  def new
  	@question = Question.find(params[:question_id])
  	@answer = Answer.new
  	@user = current_user
  end

  def create
  	question = Question.find(params[:question_id])
    answer = current_user.answers.new(answer_params)
    answer.question_id = question.id
    answer.save
    redirect_to user_questions_path
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to user_question_path(@answer.question)
  end

  def answer_params
  	params.require(:answer).permit(:user_id, :body, :question_id)
  end
end

app/controllers/user/clips_controller.rb
class User::ClipsController < ApplicationController
def create
  	temple = Temple.find(params[:temple_id])
    clip = current_user.clips.new(temple_id: temple.id)
    clip.save
    redirect_back(fallback_location: user_temples_path)
  end

  def destroy
  	temple = Temple.find(params[:temple_id])
    clip = current_user.clips.find_by(temple_id: temple.id)
    clip.destroy
    redirect_back(fallback_location: user_temples_path)
  end


end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  def new
  	@contact = Contact.new
    @user = current_user
  end

  def create
    @user = current_user
  	@contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
      if @contact.save
  	    flash[:notice] = "お問い合わせを承りました。回答につきましては、メールにてご連絡致します。"
  	    redirect_to user_user_path(@user)
      else
        render :new
      end
  end

private

  def contact_params
  	params.require(:contact).permit(:user_id, :contact)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
  	memory = Memory.find(params[:memory_id])
    favorite = current_user.favorites.new(memory_id: memory.id)
    favorite.save
    redirect_back(fallback_location: user_temples_path)
  end

  def destroy
  	memory = Memory.find(params[:memory_id])
    favorite = current_user.favorites.find_by(memory_id: memory.id)
    favorite.destroy
    redirect_back(fallback_location: user_temples_path)
  end

end

app/controllers/user/memorys_controller.rb
class User::MemorysController < ApplicationController
  PER = 10
  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Memory.find(Favorite.where(created_at: from...to).group(:memory_id).order('count(memory_id) desc').limit(10).pluck(:memory_id))
    @memorys = Memory.page(params[:page]).per(PER).order(created_at: "DESC")
  end

  def new
    @temple = Temple.find(params[:id])
  	@memory = Memory.new
    @memory.memory_images.build
  end

  def create
  	@temple = Temple.find(params[:id])
  	@memory = @temple.memorys.build(memory_params)
  	@memory.user_id = current_user.id
  	if
      @memory.save!
      redirect_to user_temple_path(@temple)
    else
      render :new
    end
  end

  def edit
    @memory = Memory.find(params[:id])
  end

  def update
    @memory = Memory.find(params[:id])
    if @memory.update(memory_params)
       flash[:notice] = "memoryを更新しました"
       redirect_to user_user_path(current_user.id)
    else
       render :edit
    end
  end

  def destroy
      @memory = Memory.find(params[:id])
      @memory.destroy
      redirect_to user_user_path(current_user.id)
  end

   private

  def memory_params
    params.require(:memory).permit(:user_id, :temple_id, :title, :body, :visit_date, memory_images_images: [])
  end
end

app/controllers/user/questions_controller.rb
class User::QuestionsController < ApplicationController
  impressionist :actions=> [:show]
  PER = 10

  def index
  	@question = Question.new
  	@questions = Question.page(params[:page]).per(PER).order(created_at: "DESC").search(params[:search])
    @most_viewed = Question.order('impressions_count DESC').take(10)
    @user = current_user
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.page(params[:page]).per(PER).order(created_at: "DESC")
    impressionist(@question, nil, unique: [:session_hash])
  end
   def create
  	@user = current_user
  	@question = Question.new(question_params)
    @question.user_id = current_user.id
      if @question.save
  	    redirect_to user_questions_path
      else
        render :index
      end
  end
  def destroy
      @question = Question.find(params[:id])
      @question.destroy
      redirect_to user_questions_path
  end

  private

  def question_params
  	params.require(:question).permit(:user_id, :body)
  end
end

app/controllers/user/temples_controller.rb
class User::TemplesController < ApplicationController
  PER = 15

  def index
    from = Time.now.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @all_ranks = Temple.find(Clip.where(created_at: from...to).group(:temple_id).order('count(temple_id) desc').limit(10).pluck(:temple_id))
    @hokkaidous = Temple.where("area = 1").page(params[:page]).per(PER)
    @touhokus = Temple.where("area = 2").page(params[:page]).per(PER)
    @kantous = Temple.where("area = 3").page(params[:page]).per(PER)
    @tyubus = Temple.where("area = 4").page(params[:page]).per(PER)
    @kinkis = Temple.where("area = 5").page(params[:page]).per(PER)
    @tyugokus = Temple.where("area = 6").page(params[:page]).per(PER)
    @sikokus = Temple.where("area = 7").page(params[:page]).per(PER)
    @kyusyus = Temple.where("area = 8").page(params[:page]).per(PER)
  end

  def show
  	@temple = Temple.find(params[:id])
  	@user = current_user
    @memorys = @temple.memorys.page(params[:page]).per(10).order(created_at: "DESC")
  end

  def edit
    @temple = Temple.find(params[:id])
  end

  def search
    @q = Temple.search(search_params)
    @temples = @q.result(distinct: true).page(params[:page]).per(15).order(created_at: "DESC")
  end

  def searchform
    @q = Temple.ransack(params[:q])
    @temples = @q.result(distinct: true)
    @goriyakus = Goriyaku.all
    @prefectures = Prefecture.all
  end


  def complete
  end


   private
  def search_params
    params.require(:q).permit!
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  PER = 10
  def show
    @user = User.find(params[:id])
    @clips = Clip.where(user_id: @user.id).all
    @memorys = @user.memorys.page(params[:page]).per(PER).order(created_at: "DESC")
    @questions = @user.questions.page(params[:page]).per(PER).order(created_at: "DESC")
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :gender, :age, :name, :profile_image, :prefecture_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
      user_temples_path
  end

  def after_sign_out_path_for(resource)
      new_user_session_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/temples_helper.rb
module Admin::TemplesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/user/temples/search.html.erb
<div class="templeheader" style="background-color: moccasin; width: 100%; margin: 0 auto; margin-bottom: 5px;">
  <ul class="nav nav-pills justify-content-center" >
    <li class="nav-item">
      <%= link_to  user_temples_path, class: "nav-link active" do %>
        <i class="fas fa-torii-gate"><span style="margin-left: 5px;">寺・神社</span></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to  user_memorys_path, class: "nav-link" do %>
        <i class="fas fa-feather-alt"><span style="margin-left: 5px;">参拝記録</span></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to  user_questions_path, class: "nav-link" do %>
        <i class="fas fa-question-circle"><span style="margin-left: 5px;">質問</span></i>
      <% end %>
    </li>
  </ul>
</div>

<h1 style="margin-top : 140px; margin-left: 170px;">検索結果</h1>

<div>
  <% if @temples.nil? %>
    <div class="row">
      <div class="col-lg-7" style="margin: 100px auto; font-size: 20px;">
        条件に一致するものがありません。<br>
        追加して欲しい寺や神社がございましたら右下の問い合わせボタンよりお問い合わせください。
      </div>
    </div>
  <% else %>
    <% @temples.each do |temple| %>
      <div class="temples">
        <%= link_to user_temple_path(temple)  do %>
          <%= attachment_image_tag temple, :mainimage, :fill, 350, 270, format: 'jpeg', fallback: "no_image.jpg",class: "temples-image" %>
          <p><%= temple.name %></p>
          <h4>(<%= temple.prefecture.name %>)</h4>
        <% end %>
      </div>
    <% end %>
    <%= paginate @temples %>
  <% end %>
</div>

app/views/user/temples/searchform.html.erb
<div class="templeheader" style="background-color: moccasin; width: 100%; margin: 0 auto; margin-bottom: 5px;">
  <ul class="nav nav-pills justify-content-center" >
    <li class="nav-item">
      <%= link_to  user_temples_path, class: "nav-link active" do %>
        <i class="fas fa-torii-gate"><span style="margin-left: 5px;">寺・神社</span></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to  user_memorys_path, class: "nav-link" do %>
        <i class="fas fa-feather-alt"><span style="margin-left: 5px;">参拝記録</span></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to  user_questions_path, class: "nav-link" do %>
        <i class="fas fa-question-circle"><span style="margin-left: 5px;">質問</span></i>
      <% end %>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-lg-7" style="margin: 0 auto; margin-top: 30px;">
    <div style="text-align: center; margin-top: 140px;">
      <%= search_form_for(@q, :url => {:controller => :temples, :action => :search}) do |f| %>
        <div style="margin-bottom: 20px;">
          <h2><i class="fas fa-search-plus">検索</i></h2>
        </div>
        <div style="margin-top: 50px;">
          <h3><i class="fas fa-torii-gate"><%= f.label :name_cont, "寺・神社名" %></i></h3>
          <%= f.search_field :name_cont %>
        </div>
        <br/>
        <div>
          <h3><i class="fas fa-money-bill-wave-alt"><%= f.label :prefecture_id_eq, "都道府県名" %></i></h3>
          <%= f.collection_select :prefecture_id_eq, @prefectures, :id, :name, :include_blank => '指定なし'%>
        </div>
        <br/>
        <div>
          <h3><i class="fas fa-praying-hands"><%= f.label :goriyaku_id_eq, "ご利益名" %></i></h3>
          <%= f.collection_select :goriyaku_id_eq, @goriyakus, :id, :name, :include_blank => '指定なし'%>
        </div>
        <br/>
        <div style="margin-top: 50px;">
          <%= f.submit '検索する' ,:style => "background-color:yellowgreen;"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/temples/show.html.erb
<div class="templeheader" style="background-color: moccasin; width: 100%; margin: 0 auto; margin-bottom: 5px;">
    <ul class="nav nav-pills justify-content-center" >
     	<li class="nav-item">
        	<%= link_to  user_temples_path, class: "nav-link active" do %>
          		<i class="fas fa-torii-gate"><span style="margin-left: 5px;">寺・神社</span></i>
        	<% end %>
      	</li>
      	<li class="nav-item">
        	<%= link_to  user_memorys_path, class: "nav-link" do %>
          		<i class="fas fa-feather-alt"><span style="margin-left: 5px;">参拝記録</span></i>
        	<% end %>
      	</li>
      	<li class="nav-item">
        	<%= link_to  user_questions_path, class: "nav-link" do %>
          		<i class="fas fa-question-circle"><span style="margin-left: 5px;">質問</span></i>
        	<% end %>
      	</li>
    </ul>
</div>
<div class="row" style="margin-top : 150px;">
	<div class="col-lg-4" style="margin-left: 50px;">
		<div>
			<div style="font-size: 50px; border-bottom: solid 3px #8b0000; text-align: center;">
				<%= @temple.name %>
				<% if @temple.cliped_by?(current_user) %>
    				<%= link_to user_temple_clips_path(@temple), method: :delete do %>
      					<i class="fa fa-star" aria-hidden="true" style="color: gold; font-size: 30px;"></i>
  			  		<% end %>
				<% else %>
    				<%= link_to user_temple_clips_path(@temple), method: :post do %>
      					<i class="far fa-star" aria-hidden="true" style="font-size: 30px; color: green;"></i>
    				<% end %>
				<% end %>
			</div>
			<div id="temple-info">
				<i class="fas fa-map-marker-alt"><%= @temple.address %></i><br>
				<i class="fas fa-praying-hands" style="margin-top: 20px;margin-right: 75px;">ご利益：<%= @temple.goriyaku.name %></i>
			</div>
		</div>
		<div id=map></div>
	</div>
	<div class="col-lg-5" style="margin-left: 50px; margin-top: 50px;">
		<div class="tab-content" id="nav-tabContent" style="text-align: center; ">
			<div class="tab-pane fade show active" id="list-mainimage" role="tabpanel" aria-labelledby="list-home-list">
				<%= attachment_image_tag @temple, :mainimage, :fill, 576, 420, format: 'jpeg' %>
			</div>
			<% @temple.temple_images.each do |image| %>
				<div class="tab-pane fade" id="list-image-<%=image.id %>" role="tabpanel" aria-labelledby="list-image-list">
					<%= attachment_image_tag image, :image, :fill, 576, 420, format: 'jpeg' %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col-lg-2" style="margin-top: 70px;">
		<div class="list-group  text-center" id="list-tab" role="tablist" style="margin-right: 20px;">
			<a class="list-group-item list-group-item-action active"  data-toggle="list" href="#list-mainimage" role="tab" aria-controls="list-mainimage">
				<%= attachment_image_tag @temple, :mainimage, :fill, 100, 70, format: 'jpeg' %>
			</a>
			<% @temple.temple_images.each do |image| %>
				<a class="list-group-item list-group-item-action" id="list-image-<%=image.id %>-list" data-toggle="list" href="#list-image-<%=image.id %>" role="tab" aria-controls="list-image">
				 	<%= attachment_image_tag image, :image, :fill, 100, 70, format: 'jpeg' %>
				</a>
			<% end %>
		</div>
	</div>
</div>
<div class="row" style="margin-top: 100px; margin-bottom: 30px;">
	<div class="col-lg-7" style="margin: 0 auto;">
		<h2 style="border-bottom: solid 3px #8b0000; text-align: center;">
			<%= @temple.name %>の投稿一覧
			<%= link_to user_new_memory_path(@temple) ,style: "font-size: 20px; " do %>
				<i class="fas fa-plus" style="margin-left: 300px; margin-right: 15px; color: darkgreen;">投稿する</i>
			<% end %>
		</h2>
		<% @memorys.each do |memory| %>
			<div class="well" style="margin-top: 30px; border: solid 1px #8b0000; padding: 10px;">
				<div style="border-bottom: dashed 1px lightgray; ">
					<%= link_to user_user_path(memory.user) ,:style=>"color:#8b0000;" do %>
						<%= attachment_image_tag memory.user, :profile_image, :fill, 50, 50, format: 'jpeg',style: "border-radius: 50%;", fallback: "no_image.jpg" %>
						<strong style="margin:10px,0,0,6px; font-size: 20px;"><%= memory.user.name %></strong>さん<br>
					<% end %>
					<p style="margin-bottom: 0px;">投稿日：<%= memory.created_at.strftime("%Y-%m-%d %H:%M") %>
						<% if memory.favorited_by?(current_user) %>
	    					<%= link_to user_memory_favorites_path(memory), method: :delete do %>
	      						<i class="fa fa-heart" aria-hidden="true" style="color:#e83b69; font-size: 20px; margin-left: 30px;"></i>
	      						<strong style="color: black; font-size: 20px; margin-left: 5px;"><%= memory.favorites.count %></strong>
	  			  			<% end %>
						<% else %>
	    					<%= link_to user_memory_favorites_path(memory), method: :post do %>
	      						<i class="far fa-heart" aria-hidden="true" style="font-size: 20px; color:#e83b69; margin-left: 30px;"></i>
	      						<strong style="color: black; font-size: 20px; margin-left: 5px;"><%= memory.favorites.count %></strong>
	    					<% end %>
						<% end %>
						<% if memory.user == current_user %>
			              	<%= link_to  user_memory_path(memory), method: :delete,"data-confirm" => "削除しますか？",style: "color:#8b0000; margin-left:350px; font-size:20px;" do %>
			                	<i class="fas fa-trash-alt"></i>
			              	<% end %>
			            <% end %>
					</p>
				</div>
				<strong style="font-size: 20px; border-bottom: solid 1px black;"><%= memory.title %></strong><br>
				<p style="font-size: 15px;">訪問日：<%= memory.visit_date %></p><br>
				<div style="margin: 0; width: 600px;">
					<%= simple_format(memory.body) %><br>
				</div>
				<% memory.memory_images.each do |image| %>
					<%= attachment_image_tag image, :image, :fill, 150, 150, format: 'jpeg' %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

<script type="text/javascript">
  function initMap() {

    var test = {lat: <%= @temple.latitude %>, lng: <%= @temple.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: test
    });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @temple.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
      position:test,
      map: map,
      title: contentString
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
</script>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyDV7aHnCQ6Lbws5KlkFCA7XzgB4So2mREE&callback=initMap">
</script>